
services:
  api:
    container_name: sipa
    build: .
    ports:
      - "30199:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=miapi;Username=miapi;Password=secret
      Jwt__Key: supersecretkey
    restart: unless-stopped

